// prisma/seed/gpu-plans.ts
// Pre-seed GPU plans — sync with E2E Networks pricing

import type { Prisma } from "@prisma/client";

export const GPU_PLANS_SEED: Prisma.GPUPlanCreateInput[] = [
  {
    e2ePlanId: "GPU.B200.1x",
    gpuName: "NVIDIA B200",
    gpuShortName: "B200",
    vram: "192GB HBM3e",
    vcpus: 26,
    ram: "250GB",
    storage: "500GB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 4.9,
    wollnutPricePerHour: 5.9,
    wollnutPricePerMinute: 0.098333,
    available: true,
    availableCount: "1x",
    sortOrder: 1,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H200.1x",
    gpuName: "NVIDIA H200",
    gpuShortName: "H200",
    vram: "141GB SXM",
    vcpus: 30,
    ram: "375GB",
    storage: "500GB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 2.2,
    wollnutPricePerHour: 2.75,
    wollnutPricePerMinute: 0.045833,
    available: true,
    availableCount: "1x, 2x, 4x, 8x",
    sortOrder: 2,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H100.1x",
    gpuName: "NVIDIA H100",
    gpuShortName: "H100",
    vram: "80GB SXM",
    vcpus: 26,
    ram: "250GB",
    storage: "500GB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 1.8,
    wollnutPricePerHour: 2.25,
    wollnutPricePerMinute: 0.0375,
    available: true,
    availableCount: "1x, 2x, 4x, 8x",
    sortOrder: 3,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H100.2x",
    gpuName: "NVIDIA H100 2x",
    gpuShortName: "H100",
    vram: "160GB SXM (2×80GB)",
    vcpus: 52,
    ram: "500GB",
    storage: "1TB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 3.6,
    wollnutPricePerHour: 4.5,
    wollnutPricePerMinute: 0.075,
    available: true,
    availableCount: "2x",
    sortOrder: 4,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H100.4x",
    gpuName: "NVIDIA H100 4x",
    gpuShortName: "H100",
    vram: "320GB SXM (4×80GB)",
    vcpus: 104,
    ram: "1TB",
    storage: "2TB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 7.2,
    wollnutPricePerHour: 9.0,
    wollnutPricePerMinute: 0.15,
    available: true,
    availableCount: "4x",
    sortOrder: 5,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H100.8x",
    gpuName: "NVIDIA H100 8x",
    gpuShortName: "H100",
    vram: "640GB SXM (8×80GB)",
    vcpus: 208,
    ram: "2TB",
    storage: "4TB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 14.4,
    wollnutPricePerHour: 18.0,
    wollnutPricePerMinute: 0.3,
    available: true,
    availableCount: "8x",
    sortOrder: 6,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H200.2x",
    gpuName: "NVIDIA H200 2x",
    gpuShortName: "H200",
    vram: "282GB SXM (2×141GB)",
    vcpus: 60,
    ram: "750GB",
    storage: "1TB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 4.4,
    wollnutPricePerHour: 5.5,
    wollnutPricePerMinute: 0.091667,
    available: true,
    availableCount: "2x",
    sortOrder: 7,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H200.4x",
    gpuName: "NVIDIA H200 4x",
    gpuShortName: "H200",
    vram: "564GB SXM (4×141GB)",
    vcpus: 120,
    ram: "1.5TB",
    storage: "2TB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 8.8,
    wollnutPricePerHour: 11.0,
    wollnutPricePerMinute: 0.183333,
    available: true,
    availableCount: "4x",
    sortOrder: 8,
    category: "gpu",
  },
  {
    e2ePlanId: "GPU.H200.8x",
    gpuName: "NVIDIA H200 8x",
    gpuShortName: "H200",
    vram: "1128GB SXM (8×141GB)",
    vcpus: 240,
    ram: "3TB",
    storage: "4TB NVMe",
    infiniband: "3.2 Tbps",
    e2ePricePerHour: 17.6,
    wollnutPricePerHour: 22.0,
    wollnutPricePerMinute: 0.366667,
    available: true,
    availableCount: "8x",
    sortOrder: 9,
    category: "gpu",
  },
];
