// prisma/seed/models.ts
// Pre-seed AI models available for one-click deploy

import type { Prisma } from "@prisma/client";

export const AI_MODELS_SEED: Prisma.AIModelCreateInput[] = [
  {
    name: "DeepSeek R1",
    slug: "deepseek-r1",
    provider: "DeepSeek",
    category: "Text-to-Text",
    description:
      "DeepSeek R1 is a 671B parameter reasoning model that achieves state-of-the-art performance on math, code, and reasoning benchmarks. Uses mixture-of-experts architecture with 37B active parameters per token. Competitive with GPT-4o and Claude 3.5 Sonnet on major benchmarks.",
    parameters: "671B",
    contextLength: "128K",
    vramRequired: "640GB minimum (8×H100 or 8×H200)",
    recommendedGpu: "H100 8x or H200 8x",
    templateSlug: "deepseek-r1-vllm",
    huggingFaceId: "deepseek-ai/DeepSeek-R1",
    licenseType: "MIT",
    featured: true,
    sortOrder: 1,
  },
  {
    name: "DeepSeek V3",
    slug: "deepseek-v3",
    provider: "DeepSeek",
    category: "Text-to-Text",
    description:
      "DeepSeek V3 is a 671B MoE model with strong general capabilities including code generation, math, multilingual tasks and instruction following. Efficient inference with only 37B active parameters.",
    parameters: "671B",
    contextLength: "128K",
    vramRequired: "640GB minimum",
    recommendedGpu: "H100 8x or H200 8x",
    templateSlug: "deepseek-v3-vllm",
    huggingFaceId: "deepseek-ai/DeepSeek-V3",
    licenseType: "MIT",
    featured: true,
    sortOrder: 2,
  },
  {
    name: "DeepSeek V3 0324",
    slug: "deepseek-v3-0324",
    provider: "DeepSeek",
    category: "Text-to-Text",
    description:
      "Updated March 2024 release of DeepSeek V3 with improved instruction following, reduced hallucination, and better coding capabilities.",
    parameters: "671B",
    contextLength: "128K",
    vramRequired: "640GB minimum",
    recommendedGpu: "H100 8x or H200 8x",
    templateSlug: "deepseek-v3-vllm",
    huggingFaceId: "deepseek-ai/DeepSeek-V3-0324",
    licenseType: "MIT",
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Llama 4 Maverick 17B 128E Instruct",
    slug: "llama-4-maverick",
    provider: "Meta",
    category: "Image-Text-to-Text",
    description:
      "Meta's Llama 4 Maverick is a 17B parameter model with 128 expert heads, supporting both text and image inputs. Optimized for instruction-following tasks with strong multimodal capabilities.",
    parameters: "17B (128 experts)",
    contextLength: "128K",
    vramRequired: "80GB minimum",
    recommendedGpu: "H100 1x or H200 1x",
    templateSlug: "llama4-vllm",
    huggingFaceId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
    licenseType: "Llama 4 Community",
    featured: true,
    sortOrder: 4,
  },
  {
    name: "Llama 4 Scout 17B 16E Instruct",
    slug: "llama-4-scout",
    provider: "Meta",
    category: "Image-Text-to-Text",
    description:
      "Meta's Llama 4 Scout is a compact 17B model with 16 expert heads. Designed for efficient deployment with strong instruction following and multimodal support.",
    parameters: "17B (16 experts)",
    contextLength: "128K",
    vramRequired: "40GB minimum",
    recommendedGpu: "H100 1x",
    templateSlug: "llama4-vllm",
    huggingFaceId: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    licenseType: "Llama 4 Community",
    featured: true,
    sortOrder: 5,
  },
  {
    name: "Hermes 3 Llama 3.1 405B",
    slug: "hermes-3-405b",
    provider: "Nous Research",
    category: "Text-to-Text",
    description:
      "Hermes 3 is a fine-tuned version of Meta's Llama 3.1 405B by Nous Research. Excels at function calling, structured outputs, roleplaying, and agentic workflows.",
    parameters: "405B",
    contextLength: "128K",
    vramRequired: "640GB minimum",
    recommendedGpu: "H100 8x or H200 4x",
    huggingFaceId: "NousResearch/Hermes-3-Llama-3.1-405B",
    licenseType: "Llama 3.1 Community",
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Stable Diffusion XL",
    slug: "stable-diffusion-xl",
    provider: "Stability AI",
    category: "Text-to-Image",
    description:
      "SDXL is Stability AI's flagship image generation model. Generates high-quality 1024×1024 images from text prompts. Supports img2img, inpainting, and ControlNet pipelines.",
    parameters: "3.5B",
    contextLength: null,
    vramRequired: "16GB minimum",
    recommendedGpu: "H100 1x",
    templateSlug: "sdxl-comfyui",
    huggingFaceId: "stabilityai/stable-diffusion-xl-base-1.0",
    licenseType: "CreativeML Open RAIL++-M",
    featured: true,
    sortOrder: 10,
  },
  {
    name: "Whisper Large v3",
    slug: "whisper-large-v3",
    provider: "OpenAI",
    category: "Speech",
    description:
      "Whisper Large v3 is OpenAI's most capable automatic speech recognition model. Supports 99 languages, translation, and timestamps. Excellent for transcription workloads.",
    parameters: "1.5B",
    contextLength: null,
    vramRequired: "10GB minimum",
    recommendedGpu: "H100 1x",
    templateSlug: "whisper-faster",
    huggingFaceId: "openai/whisper-large-v3",
    licenseType: "MIT",
    featured: false,
    sortOrder: 11,
  },
  {
    name: "CodeLlama 70B",
    slug: "codellama-70b",
    provider: "Meta",
    category: "Code",
    description:
      "CodeLlama 70B is Meta's largest code-specialized model. Trained on 500B tokens of code data. Supports code completion, generation, infilling, and instruction following.",
    parameters: "70B",
    contextLength: "16K",
    vramRequired: "140GB minimum",
    recommendedGpu: "H200 1x or H100 2x",
    huggingFaceId: "codellama/CodeLlama-70b-hf",
    licenseType: "Llama 2 Community",
    featured: false,
    sortOrder: 12,
  },
  {
    name: "Mixtral 8x22B",
    slug: "mixtral-8x22b",
    provider: "Mistral AI",
    category: "Text-to-Text",
    description:
      "Mixtral 8x22B is Mistral AI's most capable open model. MoE architecture with 176B total parameters and 39B active per token. Excels at code, math, and multilingual tasks.",
    parameters: "176B (39B active)",
    contextLength: "64K",
    vramRequired: "320GB minimum",
    recommendedGpu: "H100 4x or H200 2x",
    huggingFaceId: "mistralai/Mixtral-8x22B-Instruct-v0.1",
    licenseType: "Apache 2.0",
    featured: false,
    sortOrder: 13,
  },
  {
    name: "Phi-3",
    slug: "phi-3",
    provider: "Microsoft",
    category: "Text-to-Text",
    description:
      "Phi-3 is Microsoft's efficient small language model. Despite its small size, it achieves strong performance on reasoning and coding benchmarks, ideal for cost-efficient deployment.",
    parameters: "14B",
    contextLength: "128K",
    vramRequired: "16GB minimum",
    recommendedGpu: "H100 1x",
    huggingFaceId: "microsoft/Phi-3-medium-128k-instruct",
    licenseType: "MIT",
    featured: false,
    sortOrder: 14,
  },
  {
    name: "Gemma 2",
    slug: "gemma-2",
    provider: "Google",
    category: "Text-to-Text",
    description:
      "Gemma 2 is Google's open model optimized for efficiency. Available in 9B and 27B variants, strong performance for its size class across reasoning, coding, and multilingual tasks.",
    parameters: "27B",
    contextLength: "8K",
    vramRequired: "40GB minimum",
    recommendedGpu: "H100 1x",
    huggingFaceId: "google/gemma-2-27b-it",
    licenseType: "Gemma License",
    featured: false,
    sortOrder: 15,
  },
  {
    name: "Sarvam-2B",
    slug: "sarvam-2b",
    provider: "Sarvam AI",
    category: "Text-to-Text",
    description:
      "Sarvam-2B is an Indian-language-first model supporting 10+ Indic languages including Hindi, Tamil, Telugu, Bengali, and more. Optimized for Indian enterprise use cases.",
    parameters: "2B",
    contextLength: "4K",
    vramRequired: "8GB minimum",
    recommendedGpu: "H100 1x",
    huggingFaceId: "sarvamai/sarvam-2b-v0.5",
    licenseType: "Apache 2.0",
    featured: false,
    sortOrder: 16,
  },
  {
    name: "Dolphin 2.9.2 Mixtral 8x22B",
    slug: "dolphin-mixtral-8x22b",
    provider: "Cognitive Computations",
    category: "Text-to-Text",
    description:
      "Dolphin is an uncensored fine-tune of Mixtral 8x22B by Eric Hartford. Optimized for helpfulness, creativity, and system prompt following. Strong at function calling and agentic tasks.",
    parameters: "176B (39B active)",
    contextLength: "64K",
    vramRequired: "320GB minimum",
    recommendedGpu: "H100 4x or H200 2x",
    huggingFaceId: "cognitivecomputations/dolphin-2.9.2-mixtral-8x22b",
    licenseType: "Apache 2.0",
    featured: false,
    sortOrder: 17,
  },
];
