// prisma/seed/templates.ts
// Pre-seed templates mapping to E2E Networks images

import type { Prisma } from "@prisma/client";

export const TEMPLATES_SEED: Prisma.TemplateCreateInput[] = [
  {
    name: "PyTorch 2.2 + CUDA 12.4",
    slug: "pytorch-cuda",
    description:
      "Production-ready PyTorch environment with CUDA 12.4, cuDNN 9.0, and NCCL for multi-GPU training. Includes JupyterLab, common data science libraries, and optimized NVIDIA drivers.",
    category: "General ML",
    e2eImageId: "pytorch-2.2-cuda-12.4",
    icon: "pytorch",
    tags: ["pytorch", "cuda", "deep-learning", "training"],
    includedPackages: [
      "PyTorch 2.2",
      "CUDA 12.4",
      "cuDNN 9.0",
      "NCCL 2.20",
      "JupyterLab 4.x",
      "Python 3.11",
      "NumPy",
      "Pandas",
      "Matplotlib",
    ],
    recommendedGpu: "H100 or H200",
    minVram: "24GB",
    featured: true,
    sortOrder: 1,
  },
  {
    name: "TensorFlow 2.16 + CUDA 12.4",
    slug: "tensorflow-cuda",
    description:
      "TensorFlow environment with full GPU acceleration. Includes Keras 3, TensorBoard, and TFX pipeline tools. Pre-configured for distributed training with tf.distribute.",
    category: "General ML",
    e2eImageId: "tensorflow-2.16-cuda-12.4",
    icon: "tensorflow",
    tags: ["tensorflow", "keras", "cuda", "training"],
    includedPackages: [
      "TensorFlow 2.16",
      "Keras 3.0",
      "CUDA 12.4",
      "cuDNN 9.0",
      "TensorBoard",
      "JupyterLab 4.x",
      "Python 3.11",
    ],
    recommendedGpu: "H100 or A100",
    minVram: "24GB",
    featured: true,
    sortOrder: 2,
  },
  {
    name: "vLLM Inference Server",
    slug: "vllm-inference",
    description:
      "High-throughput LLM inference with vLLM. PagedAttention for efficient memory management, continuous batching, and OpenAI-compatible API endpoint. Ideal for deploying any HuggingFace model.",
    category: "LLM Inference",
    e2eImageId: "vllm-latest-cuda-12.4",
    icon: "vllm",
    tags: ["vllm", "inference", "llm", "serving", "api"],
    includedPackages: [
      "vLLM 0.6.x",
      "CUDA 12.4",
      "Python 3.11",
      "HuggingFace Transformers",
      "Flash Attention 2",
      "Ray",
    ],
    recommendedGpu: "H100 or H200",
    minVram: "40GB",
    featured: true,
    sortOrder: 3,
  },
  {
    name: "LLM Fine-tuning (LoRA/QLoRA)",
    slug: "llm-finetuning",
    description:
      "Pre-configured for efficient LLM fine-tuning with LoRA, QLoRA, and full fine-tuning support. Includes Unsloth, PEFT, TRL, and Axolotl for easy training pipeline setup.",
    category: "LLM Training",
    e2eImageId: "finetuning-cuda-12.4",
    icon: "finetune",
    tags: ["fine-tuning", "lora", "qlora", "llm", "training", "unsloth"],
    includedPackages: [
      "Unsloth",
      "PEFT",
      "TRL",
      "Axolotl",
      "bitsandbytes",
      "Flash Attention 2",
      "Weights & Biases",
      "CUDA 12.4",
      "Python 3.11",
    ],
    recommendedGpu: "H100 or H200",
    minVram: "40GB",
    featured: true,
    sortOrder: 4,
  },
  {
    name: "ComfyUI (Stable Diffusion)",
    slug: "comfyui-sdxl",
    description:
      "Node-based UI for Stable Diffusion workflows. Pre-loaded with SDXL, popular ControlNet models, and common extensions. Web UI accessible via browser.",
    category: "Image Generation",
    e2eImageId: "comfyui-sdxl-cuda-12.4",
    icon: "comfyui",
    tags: ["stable-diffusion", "sdxl", "comfyui", "image-generation", "diffusion"],
    includedPackages: [
      "ComfyUI",
      "SDXL Base + Refiner",
      "ControlNet Models",
      "IP-Adapter",
      "CUDA 12.4",
      "Python 3.11",
    ],
    recommendedGpu: "H100 1x",
    minVram: "16GB",
    featured: false,
    sortOrder: 5,
  },
  {
    name: "JAX + TPU/GPU",
    slug: "jax-gpu",
    description:
      "Google JAX environment with XLA compilation for GPU. Includes Flax, Optax, and Orbax. Ideal for research workloads requiring JIT compilation and functional programming patterns.",
    category: "General ML",
    e2eImageId: "jax-latest-cuda-12.4",
    icon: "jax",
    tags: ["jax", "flax", "xla", "research"],
    includedPackages: [
      "JAX 0.4.x",
      "Flax",
      "Optax",
      "Orbax",
      "CUDA 12.4",
      "Python 3.11",
      "JupyterLab 4.x",
    ],
    recommendedGpu: "H100 or H200",
    minVram: "40GB",
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Ubuntu 22.04 + CUDA (Bare)",
    slug: "ubuntu-cuda-bare",
    description:
      "Minimal Ubuntu 22.04 with CUDA toolkit and NVIDIA drivers. No ML frameworks pre-installed — bring your own stack. SSH and JupyterLab access configured.",
    category: "Bare Metal",
    e2eImageId: "ubuntu-22.04-cuda-12.4",
    icon: "ubuntu",
    tags: ["ubuntu", "cuda", "bare", "custom"],
    includedPackages: [
      "Ubuntu 22.04 LTS",
      "CUDA 12.4",
      "NVIDIA Driver 550",
      "Python 3.11",
      "Docker",
      "JupyterLab 4.x",
    ],
    recommendedGpu: "Any",
    minVram: "16GB",
    featured: false,
    sortOrder: 10,
  },
  {
    name: "Whisper + Faster Whisper",
    slug: "whisper-faster",
    description:
      "Optimized speech-to-text environment with OpenAI Whisper and Faster Whisper (CTranslate2 backend). Includes a REST API server for batch transcription.",
    category: "Speech",
    e2eImageId: "whisper-cuda-12.4",
    icon: "whisper",
    tags: ["whisper", "speech", "transcription", "stt"],
    includedPackages: [
      "Whisper",
      "Faster Whisper",
      "CTranslate2",
      "CUDA 12.4",
      "Python 3.11",
      "FastAPI",
    ],
    recommendedGpu: "H100 1x",
    minVram: "10GB",
    featured: false,
    sortOrder: 7,
  },
  {
    name: "DeepSeek R1 (vLLM)",
    slug: "deepseek-r1-vllm",
    description:
      "One-click deploy of DeepSeek R1 671B with vLLM. Pre-configured for multi-GPU inference with tensor parallelism. OpenAI-compatible API endpoint included.",
    category: "LLM Inference",
    e2eImageId: "deepseek-r1-vllm",
    icon: "deepseek",
    tags: ["deepseek", "r1", "reasoning", "llm", "inference"],
    includedPackages: [
      "DeepSeek R1 671B weights",
      "vLLM 0.6.x",
      "CUDA 12.4",
      "Flash Attention 2",
      "Tensor Parallelism",
    ],
    recommendedGpu: "H100 8x or H200 8x",
    minVram: "640GB",
    featured: true,
    sortOrder: 0,
  },
];
